'use strict';

const WORKMODE_ROBOT_IDLE           = 'idle';
const WORKMODE_ROBOT_CLEANING       = 'cleaning';

const WORKMODE_STATION_IDLE         = 'idle';
const WORKMODE_STATION_WASHING      = 'washing';
const WORKMODE_STATION_DRYING       = 'drying';
const WORKMODE_STATION_GOCHARGING   = 'goCharging';
const WORKMODE_STATION_GOWASHING    = 'goWashing';
const WORKMODE_STATION_EMPTYING     = 'emptying';





module.exports = Object.freeze({
    WORKMODE_ROBOT_IDLE,
    WORKMODE_ROBOT_CLEANING,
    WORKMODE_STATION_IDLE,
    WORKMODE_STATION_WASHING,
    WORKMODE_STATION_DRYING,
    WORKMODE_STATION_GOCHARGING,
    WORKMODE_STATION_GOWASHING,
    WORKMODE_STATION_EMPTYING
})